services:
  postgres:
    image: postgres:16
    container_name: payment-api
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment-api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: