### Create a new customer
POST http://localhost:3000/api/customers
Content-Type: application/json

{
  "name": "COMPAÑIA PRINSS E.I.R.L",
  "tax_id": "20613088483",
  "address": "AV. ALEJANDRO TIRADO NRO. 762 URB. SANTA BEATRIZ LIMA - LIMA - LIMA"
}
### Create a new customer
POST http://localhost:3000/api/customers
Content-Type: application/json

{
  "name": "W & M PRODUCTOS DE LIMPIEZA E.I.R.L",
  "tax_id": "20554898158",
  "address": "CAL.SANTA ROSA MZA. O LOTE. 25 URB. LAS FRESAS PROV. CONST. DEL CALLAO - PROV. CONST. DEL CALLAO - CALLAO"
}

### Get all customers
GET http://localhost:3000/api/customers

###

### Get a customer by ID
GET http://localhost:3000/api/customers/2

###

### Update a customer
PUT http://localhost:3000/api/customers/2
Content-Type: application/json

{
  "name": "Juan Pérez Modificado2",
  "tax_id": "1234567890",
  "address": "Calle Falsa 456"
}

###

### Delete a customer
DELETE http://localhost:3000/api/customers/7