### Create a new invoice
POST http://localhost:3000/api/invoices
Content-Type: application/json

{
  "customer_id": 8,
  "collector_id": 3,
  "issue_date": "2025-06-13T00:00:00.000Z",
  "total": 150.75,
  "comments": "Pago parcial por servicios",
  "payment_method": "credit",
  "payment_channel": "factura",
  "status": "partial"
}

## Get all customers
GET http://localhost:3000/api/invoices

### Get a customer by ID
GET http://localhost:3000/api/invoices/1
### Update an invoice
PUT http://localhost:3000/api/invoices/1
Content-Type: application/json

{
  "total": 200.00,
  "comments": "Monto corregido",
  "status": "paid"
}

### Delete Invoice
DELETE http://localhost:3000/api/invoices/1